"""AddBreedToPuppyTable

Revision ID: 8a3b77fd199c
Revises: 
Create Date: 2020-08-31 20:49:35.459977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3b77fd199c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Puppies', 'breed')
    # ### end Alembic commands ###
